name: Deploy To Portal Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEV_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.CCOLLINS1544_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pm2 stop azure_spa_main
            cd /home/ubuntu/azure_spa_main/source
            git reset --hard HEAD
            git pull 
            npm install 
            rsync -avu /home/ubuntu/azure_spa_main/source/assets/pm2/ecosystem.config.js /home/ubuntu/ecosystem.config.js
            pm2 start /home/ubuntu/ecosystem.config.js --only azure_spa_main --env production
